version: '3.8'

services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - modhub_network

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - modhub_network

  usersservice:
    build:
      context: ./src/Services/Users
      dockerfile: Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__MongoDb=mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongodb:27017
      - JWT__Secret=${JWT_SECRET}
      - JWT__ExpiryMinutes=60
      - JWT__Issuer=ModsGamingPlatform
      - JWT__Audience=ModsGamingPlatformUsers
      - REDIS__ConnectionString=redis:6379
    depends_on:
      - mongodb
      - redis
    networks:
      - modhub_network

  modsservice:
    build:
      context: ./src/Services/Mods
      dockerfile: Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__MongoDb=mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongodb:27017
    depends_on:
      - mongodb
    volumes:
      - mod_files:/app/mod-files
    networks:
      - modhub_network

  paymentsservice:
    build:
      context: ./src/Services/Payments
      dockerfile: Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__MongoDb=mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongodb:27017
      - Stripe__SecretKey=${STRIPE_SECRET_KEY}
      - Stripe__WebhookSecret=${STRIPE_WEBHOOK_SECRET}
    depends_on:
      - mongodb
    networks:
      - modhub_network

  communityservice:
    build:
      context: ./src/Services/Community
      dockerfile: Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__MongoDb=mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongodb:27017
      - REDIS__ConnectionString=redis:6379
    depends_on:
      - mongodb
      - redis
    networks:
      - modhub_network

  gateway:
    build:
      context: ./src/Gateway
      dockerfile: Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Services__UsersService=http://usersservice
      - Services__ModsService=http://modsservice
      - Services__PaymentsService=http://paymentsservice
      - Services__CommunityService=http://communityservice
      - JWT__Secret=${JWT_SECRET}
    depends_on:
      - usersservice
      - modsservice
      - paymentsservice
      - communityservice
    networks:
      - modhub_network

  frontend:
    build:
      context: ./src
      dockerfile: Frontend/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - BackendUrl=https://${DOMAIN_NAME}/api
    depends_on:
      - gateway
    networks:
      - modhub_network

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ./docker/letsencrypt/live/modhub.fr:/etc/nginx/ssl:ro
      - ./docker/letsencrypt/www:/var/www/certbot:rw
    depends_on:
      - frontend
      - gateway
    networks:
      - modhub_network

  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - modhub_network

  grafana:
    image: grafana/grafana:latest
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
    networks:
      - modhub_network

volumes:
  mongodb_data:
  redis_data:
  mod_files:
  prometheus_data:
  grafana_data:

networks:
  modhub_network:
    driver: bridge
