global:
  resolve_timeout: 5m
  smtp_from: 'alertmanager@modhub.example.com'
  smtp_smarthost: 'smtp.example.com:587'
  smtp_auth_username: 'alerts@modhub.example.com'
  smtp_auth_password: '${SMTP_PASSWORD}'
  smtp_require_tls: true

# Configuration des routes et de leur correspondance
route:
  group_by: ['job', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'team-ops'
  routes:
    - match:
        severity: critical
      receiver: 'team-ops'
      repeat_interval: 1h
    - match:
        severity: warning
      receiver: 'team-ops'
      repeat_interval: 3h

# Configuration des récepteurs pour les notifications
receivers:
- name: 'team-ops'
  email_configs:
  - to: 'ops@modhub.example.com'
    send_resolved: true
  slack_configs:
  - api_url: '${SLACK_WEBHOOK}'
    channel: '#alerts'
    send_resolved: true
    title: |-
      [{{ .Status | toUpper }}] {{ .CommonLabels.alertname }}
    text: |-
      {{ range .Alerts }}
      *Alerte:* {{ .Annotations.summary }}
      *Description:* {{ .Annotations.description }}
      *Gravité:* {{ .Labels.severity }}
      *Depuis:* {{ .StartsAt }}
      {{ end }}

# Définition des templates
templates:
  - '/etc/alertmanager/template/*.tmpl'

# Inhibition rules (règles qui suppriment certaines alertes si d'autres sont actives)
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['job']
