global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'dotnet-services'
    static_configs:
      - targets: 
          - 'gateway:8080'
          - 'usersservice:5001'
          - 'modsservice:5002'
          - 'paymentsservice:5003'
          - 'communityservice:5004'
          - 'frontend:5000'