apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 10s
      queryTimeout: 30s
      httpMethod: POST
    version: 1

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    database: "[logs-]YYYY.MM.DD"
    url: http://elasticsearch:9200
    jsonData:
      index: "logstash-*"
      timeField: "@timestamp"
      esVersion: 7.0.0
      logLevelField: level
      logMessageField: message
    editable: true
